version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_DATABASES: auth_service,wallet_service,kyc_service,liquidity_service,notification_service
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres:/docker-entrypoint-initdb.d
    networks:
      - app_network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app_network

  auth_service:
    build:
      context: ./services/auth-service
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/auth_service?schema=public
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    networks:
      - app_network

  wallet_service:
    build:
      context: ./services/wallet-service
      dockerfile: Dockerfile
    ports:
      - "3334:3334"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/wallet_service?schema=public
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    networks:
      - app_network

  kyc_service:
    build:
      context: ./services/kyc
      dockerfile: Dockerfile
    ports:
      - "3335:3335"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/kyc_service?schema=public
    depends_on:
      - postgres
    networks:
      - app_network

  liquidity_service:
    build:
      context: ./services/liquidity
      dockerfile: Dockerfile
    ports:
      - "3336:3336"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/liquidity_service?schema=public
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    networks:
      - app_network

  notification_service:
    build:
      context: ./services/notification-service
      dockerfile: Dockerfile
    ports:
      - "3337:3337"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/notification_service?schema=public
      - REDIS_URL=redis://redis:6379
    depends_on:
      - postgres
      - redis
    networks:
      - app_network

  admin:
    build:
      context: ./crypto-wallet-admin
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://auth_service:3333
    depends_on:
      - auth_service
      - wallet_service
      - kyc_service
      - liquidity_service
      - notification_service
    networks:
      - app_network

volumes:
  postgres_data:
  redis_data:

networks:
  app_network:
    driver: bridge