export enum KYCLevel {
  LEVEL_0 = 'LEVEL_0',
  LEVEL_1 = 'LEVEL_1',
  LEVEL_2 = 'LEVEL_2',
  LEVEL_3 = 'LEVEL_3',
}

export enum KYCStatus {
  PENDING = 'PENDING',
  IN_PROGRESS = 'IN_PROGRESS',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum Network {
  POLYGON = 'POLYGON',
  BSC = 'BSC',
  ETHEREUM = 'ETHEREUM',
}

export enum TransactionType {
  DEPOSIT = 'DEPOSIT',
  WITHDRAWAL = 'WITHDRAWAL',
  TRANSFER = 'TRANSFER',
  EXCHANGE = 'EXCHANGE',
  BUY = 'BUY',
  SELL = 'SELL',
  INCOMING = 'INCOMING',
  OUTGOING = 'OUTGOING',
}

export enum TransactionStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  CANCELLED = 'CANCELLED',
}

export enum WhatsAppPriority {
  CRITICAL = 'CRITICAL',
  HIGH = 'HIGH',
  MEDIUM = 'MEDIUM',
  LOW = 'LOW',
}

export enum AlertType {
  SUSPICIOUS_TRANSACTION = 'SUSPICIOUS_TRANSACTION',
  LARGE_TRANSACTION = 'LARGE_TRANSACTION',
  UNUSUAL_PATTERN = 'UNUSUAL_PATTERN',
  NETWORK_CONGESTION = 'NETWORK_CONGESTION',
  HIGH_GAS_PRICE = 'HIGH_GAS_PRICE',
  SECURITY_BREACH = 'SECURITY_BREACH',
  GUARDIAN_REQUIRED = 'GUARDIAN_REQUIRED',
  BLACKLISTED_ADDRESS = 'BLACKLISTED_ADDRESS',
  RATE_LIMIT_EXCEEDED = 'RATE_LIMIT_EXCEEDED',
  SYSTEM_ERROR = 'SYSTEM_ERROR'
}

export enum AlertSeverity {
  INFO = 'INFO',
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  CRITICAL = 'CRITICAL'
}