adminUser: admin
adminPassword: admin

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Prometheus
        type: prometheus
        url: http://prometheus-server
        access: proxy
        isDefault: true
      - name: CloudWatch
        type: cloudwatch
        jsonData:
          authType: default
          defaultRegion: us-east-1

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: 'default'
        orgId: 1
        folder: ''
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards

dashboards:
  default:
    overview:
      gnetId: 1860
      revision: 23
      datasource: Prometheus

    node-exporter:
      gnetId: 1860
      revision: 23
      datasource: Prometheus

    crypto-wallet:
      file: dashboards/crypto-wallet.json

persistence:
  enabled: true
  size: 10Gi

service:
  type: ClusterIP

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - grafana.staging.example.com
  tls:
    - secretName: grafana-tls
      hosts:
        - grafana.staging.example.com

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

plugins:
  - grafana-piechart-panel
  - grafana-worldmap-panel
  - grafana-clock-panel

env:
  GF_AUTH_DISABLE_LOGIN_FORM: "true"
  GF_AUTH_ANONYMOUS_ENABLED: "false"
  GF_AUTH_BASIC_ENABLED: "false"
  GF_AUTH_PROXY_ENABLED: "true"
  GF_AUTH_PROXY_HEADER_NAME: "X-WEBAUTH-USER"
  GF_AUTH_PROXY_HEADER_PROPERTY: "username"
  GF_AUTH_PROXY_AUTO_SIGN_UP: "true"
  GF_AUTH_PROXY_SYNC_TTL: "60"
  GF_SECURITY_ALLOW_EMBEDDING: "true"
  GF_SECURITY_COOKIE_SECURE: "true"
  GF_SECURITY_COOKIE_SAMESITE: "strict"

sidecar:
  dashboards:
    enabled: true
    searchNamespace: ALL
    provider:
      foldersFromFilesStructure: true
  datasources:
    enabled: true
    searchNamespace: ALL

serviceMonitor:
  enabled: true
  namespace: monitoring

prometheusRule:
  enabled: true
  namespace: monitoring
  rules:
    - alert: GrafanaDown
      expr: absent(up{job="grafana"})
      for: 5m
      labels:
        severity: critical
      annotations:
        description: Grafana has been down for more than 5 minutes.
        summary: Grafana is down

dashboardsConfigMaps:
  - configMapName: grafana-dashboards
    fileName: crypto-wallet.json
    content: |
      {
        "annotations": {
          "list": [
            {
              "builtIn": 1,
              "datasource": "-- Grafana --",
              "enable": true,
              "hide": true,
              "iconColor": "rgba(0, 211, 255, 1)",
              "name": "Annotations & Alerts",
              "type": "dashboard"
            }
          ]
        },
        "editable": true,
        "gnetId": null,
        "graphTooltip": 0,
        "id": null,
        "links": [],
        "panels": [
          {
            "aliasColors": {},
            "bars": false,
            "dashLength": 10,
            "dashes": false,
            "datasource": "Prometheus",
            "fill": 1,
            "gridPos": {
              "h": 8,
              "w": 12,
              "x": 0,
              "y": 0
            },
            "id": 2,
            "legend": {
              "avg": false,
              "current": false,
              "max": false,
              "min": false,
              "show": true,
              "total": false,
              "values": false
            },
            "lines": true,
            "linewidth": 1,
            "links": [],
            "nullPointMode": "null",
            "percentage": false,
            "pointradius": 5,
            "points": false,
            "renderer": "flot",
            "seriesOverrides": [],
            "spaceLength": 10,
            "stack": false,
            "steppedLine": false,
            "targets": [
              {
                "expr": "rate(http_requests_total[5m])",
                "format": "time_series",
                "intervalFactor": 1,
                "legendFormat": "{{status}}",
                "refId": "A"
              }
            ],
            "thresholds": [],
            "timeFrom": null,
            "timeShift": null,
            "title": "Request Rate",
            "tooltip": {
              "shared": true,
              "sort": 0,
              "value_type": "individual"
            },
            "type": "graph",
            "xaxis": {
              "buckets": null,
              "mode": "time",
              "name": null,
              "show": true,
              "values": []
            },
            "yaxes": [
              {
                "format": "short",
                "label": null,
                "logBase": 1,
                "max": null,
                "min": null,
                "show": true
              },
              {
                "format": "short",
                "label": null,
                "logBase": 1,
                "max": null,
                "min": null,
                "show": true
              }
            ]
          }
        ],
        "schemaVersion": 16,
        "style": "dark",
        "tags": [],
        "templating": {
          "list": []
        },
        "time": {
          "from": "now-6h",
          "to": "now"
        },
        "timepicker": {
          "refresh_intervals": [
            "5s",
            "10s",
            "30s",
            "1m",
            "5m",
            "15m",
            "30m",
            "1h",
            "2h",
            "1d"
          ],
          "time_options": [
            "5m",
            "15m",
            "1h",
            "6h",
            "12h",
            "24h",
            "2d",
            "7d",
            "30d"
          ]
        },
        "timezone": "",
        "title": "Crypto Wallet Overview",
        "uid": null,
        "version": 0
      }
